#server:
#  port: 8761
#spring:
#  profiles: master
#eureka:
#  instance:
#    hostname: 127.0.0.1
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#
#

server:
  port: 8761
spring:
  profiles: slave1
  application:
    name: evyn-server
eureka:
  instance:
    hostname: slave1
    prefer-ip-address: true #注册地址到eureka
  server:
    enable-self-preservation: false #关闭自我保护模式
    eviction-interval-timer-in-ms: 5000 #每隔10秒清理一次服务  默认60秒
  client:
    registerWithEureka: true #将自己也注册到服务
    fetchRegistry: true #获取注册信息
    serviceUrl:
      defaultZone: http://slave2:8762/eureka/

logging:
  level:
    com.netflex: debug
---

server:
  port: 8762
spring:
  profiles: slave2
  application:
    name: evyn-server
eureka:
  instance:
    hostname: slave2
    prefer-ip-address: true
  server:
    enable-self-preservation: false #关闭自我保护模式
    eviction-interval-timer-in-ms: 5000 #每隔10秒清理一次服务  默认60秒
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://slave1:8761/eureka/
logging:
  level:
    com.netflex: debug