server:
  port: 9000
spring:
  application:
    name: zuul_gateway
  main:
    allow-bean-definition-overriding: true
zuul:
  routes:
    zuultest:
      path: /c/**
      serviceId: client

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/
management:
  security:
    enabled: false
